[project]
name = "reportlens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sriman", email = "srimanchaudhuri@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "llama-cloud-services>=0.6.94",
    "llama-index>=0.14.25",
    "llama-parse>=0.6.94",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
reportlens = "reportlens:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
